
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AUTERION_CI_DOCKERHUB_USER }}
          password: ${{ secrets.AUTERION_CI_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: auterion/commitlint:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}
          release-type: simple
          package-name: docker-commitlint

      - name: Create tagged docker image
        if: steps.release-please.outputs.release_created
        run: |
          docker pull auterion/commitlint:latest
          docker tag auterion/commitlint:latest auterion/commitlint:${{ steps.release-please.outputs.tag_name }}
          docker push auterion/commitlint:${{ steps.release-please.outputs.tag_name }}
